2022-09-01 12:39:07,680 ERROR com.bankingservice.banking.services.CardService [main] [] [] [generateCardDetails] card already exists for userId: dxCwVUaFol
2022-09-01 12:39:07,839 ERROR com.bankingservice.banking.services.CardService [main] [] [] [generateCardDetails] user does not exist with user ID: dxCwVUaFol
2022-09-01 12:39:08,339 ERROR com.bankingservice.banking.services.CardService [main] [] [] [getCardDetails] card does not exist for user ID : dxCwVUaFol
2022-09-01 12:39:08,446 ERROR com.bankingservice.banking.services.CardService [main] [] [] [getCardDetails] user does not exist for user ID : dxCwVUaFol
2022-09-01 12:39:08,721 ERROR com.bankingservice.banking.services.CardService [main] [] [] [setPin] card not found for card number: 4093169052473964296
2022-09-01 12:41:24,265 ERROR com.bankingservice.banking.services.AccountService [main] [] [] [getUserDetails] user does not exist for user ID : 0cZ2zxmxif
2022-09-01 12:41:24,862 ERROR com.bankingservice.banking.services.AccountService [main] [] [] [saveRegisterModel] account already exists for userId: 0cZ2zxmxif
2022-09-01 12:41:25,309 ERROR com.bankingservice.banking.services.AccountService [main] [] [] [insertDetailsForRegistration] details insertion failed in db for request: RegisterRequestDTO(name=cIqTTYmHwo, email=aCXg8FQwF7, mobileNumber=3212594560511865771, userName=XZgiCFZLzm, password=XVjvdKBdX0)
org.springframework.dao.DataIntegrityViolationException: 
	at mockit.internal.expectations.invocation.InvocationResult$ThrowableResult.produceResult(InvocationResult.java:41)
	at mockit.internal.expectations.invocation.InvocationResult.produceResult(InvocationResult.java:22)
	at mockit.internal.expectations.invocation.InvocationResults.produceResult(InvocationResults.java:124)
	at mockit.internal.expectations.Expectation.produceResult(Expectation.java:48)
	at mockit.internal.expectations.ReplayPhase.produceResult(ReplayPhase.java:108)
	at mockit.internal.expectations.ReplayPhase.handleInvocation(ReplayPhase.java:52)
	at mockit.internal.expectations.RecordAndReplayExecution.recordOrReplay(RecordAndReplayExecution.java:170)
	at com.bankingservice.banking.services.servicehelper.AccountServiceHelper.saveRegisterModel(AccountServiceHelper.java)
	at com.bankingservice.banking.services.AccountService.insertDetailsForRegistration(AccountService.java:46)
	at com.bankingservice.banking.services.AccountServiceTest.testInsertDetailsForRegistrationException(AccountServiceTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
2022-09-01 12:43:01,382 ERROR com.bankingservice.banking.services.CardService [main] [] [] [generateCardDetails] card already exists for userId: Krj63z1JMb
2022-09-01 12:43:01,574 ERROR com.bankingservice.banking.services.CardService [main] [] [] [generateCardDetails] user does not exist with user ID: Krj63z1JMb
2022-09-01 12:43:02,215 ERROR com.bankingservice.banking.services.CardService [main] [] [] [getCardDetails] card does not exist for user ID : Krj63z1JMb
2022-09-01 12:43:02,360 ERROR com.bankingservice.banking.services.CardService [main] [] [] [getCardDetails] user does not exist for user ID : Krj63z1JMb
2022-09-01 12:43:02,730 ERROR com.bankingservice.banking.services.CardService [main] [] [] [setPin] card not found for card number: 4204396130934951740
2022-09-01 12:43:03,779 ERROR com.bankingservice.banking.services.AccountService [main] [] [] [getUserDetails] user does not exist for user ID : GZhTCjQonA
2022-09-01 12:43:04,522 ERROR com.bankingservice.banking.services.AccountService [main] [] [] [saveRegisterModel] account already exists for userId: GZhTCjQonA
2022-09-01 12:43:05,115 ERROR com.bankingservice.banking.services.AccountService [main] [] [] [insertDetailsForRegistration] details insertion failed in db for request: RegisterRequestDTO(name=ookcDNSWEC, email=Bph82qc0an, mobileNumber=5782493553765092593, userName=TjM42KHlQ2, password=ZAaXOEr1F0)
org.springframework.dao.DataIntegrityViolationException: 
	at mockit.internal.expectations.invocation.InvocationResult$ThrowableResult.produceResult(InvocationResult.java:41)
	at mockit.internal.expectations.invocation.InvocationResult.produceResult(InvocationResult.java:22)
	at mockit.internal.expectations.invocation.InvocationResults.produceResult(InvocationResults.java:124)
	at mockit.internal.expectations.Expectation.produceResult(Expectation.java:48)
	at mockit.internal.expectations.ReplayPhase.produceResult(ReplayPhase.java:108)
	at mockit.internal.expectations.ReplayPhase.handleInvocation(ReplayPhase.java:52)
	at mockit.internal.expectations.RecordAndReplayExecution.recordOrReplay(RecordAndReplayExecution.java:170)
	at com.bankingservice.banking.services.servicehelper.AccountServiceHelper.saveRegisterModel(AccountServiceHelper.java)
	at com.bankingservice.banking.services.AccountService.insertDetailsForRegistration(AccountService.java:46)
	at com.bankingservice.banking.services.AccountServiceTest.testInsertDetailsForRegistrationException(AccountServiceTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
